### ISSUE TITLE
Incompatibilità schede micro SD?

### ISSUE THREAD

**Issue by repetto74** [aotta/RTO-Cart#1]
Ciao

Bellissimo progetto per la Intellivision che aspettavo da tempo :-).
Avendo un Teensy 4.1 nel cassetto mi sono deciso a montare questa RTO. Tutto sembrava funzionare in un primo momento usando i binari TOSEC della Intellivision e abbinando il file .cfg.
Purtroppo dopo una seconda prova, il Teensy non vede piu i binari registrati sulla SD. Sono state segnalate incompatibilità con alcune schede SD? Le ho prese su Ali a poco prezzo dunque non so quanto siano affidabili :-). 
Possibilità di avere un HEX corrotto sul Teensy? (possibilità remota penso).
Grazie e complimenti :-)
Rick

**Comment by aotta** [comment]
Ciao, no fino ad ora nessun problema segnalato con le sd, anche se
ovviamente non sono state create ancora molte rto, o almeno quelle di cui
ho notizia. Ti consiglio di flashare la teensy con uno dei programmi di
prova della libreria sd per escludere problemi con quella.
Ma hai per caso flashato la versione 1.1a? Nella versione beta all'avvio
non legge subito la scheda.
Buona fortuna con le prove e saluti
Andrea

Il dom 5 feb 2023, 18:50 repetto74 ***@***.***> ha scritto:

**Comment by repetto74** [comment]
Ciao Andrea :-)
Non so a quale programma ti riferisci. Io ho flashato il Teensy usando il file RTO.ino disponibile nella cartella del progetto. Per fare cio' ho dovuto installare il modulo di gestione delle Teensy su Arduino IDE (piu alcune librerie mancanti) e flashare da l'IDE. Ha funzionato al primo colpo ma poi ha deciso di non farmi più vedere i .bin presenti nella SD.

**Comment by aotta** [comment]
Intendo i programmi che dovresti trovare dall'IDE in File/esempi/SD, sono
programmi che leggono le info della SDCard e la testano in scrittura e
lettura.
Se quelli funzionano, non è un problema della SDCard.
Puoi anche provare sempre da IDE arduino a lanciare il "monitor seriale", e
leggere se da qualche messaggio di errore la RTO (anche se dovrebbe darli
sullo schermo oled, cosa che immagino non hai).

Il giorno dom 5 feb 2023 alle ore 19:04 repetto74 ***@***.***>
ha scritto:

**Comment by repetto74** [comment]
No nessun messaggio di errore sullo schermo OLED. Ho creato una cartella per gioco dove inserire il .bin e .cfg. Posso navigare tranquillamente nelle varie cartelle ma risultano tutte vuote.

**Comment by repetto74** [comment]
Ciao :-). Ho provato con una micro SD di buona marca e tutto ok. Dunque le micro SD scadenti possono dare problemi in lettura.
Grazie per questa bella scheda ;-)
Riccardo

**Comment by aotta** [comment]
Benissimo, chiudo la issue, che comunque è legata al lettore integrato nella Teensy 4.1, non al progetto RTO.
