### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by pmgducati** [aotta/RTO-Cart#2]
Can you post a Bill of Materials?

**Comment by pmgducati** [comment]
I installed KiCAD and found all the component Values.  The only thing that I am missing is the OLED screen.  Can you provide a source for that?

**Comment by aotta** [comment]
You can simply search for "oled 128x32 i2c display” on popular web markets

Il ven 29 set 2023, 22:15 pmgducati ***@***.***> ha scritto:

**Comment by pmgducati** [comment]
Perfect, thanks!
